trigger:
- main

variables:
  vmName: 'multi-stage-vm'
  vmAdmin: 'ishwar59'
  vmPassword: 'Ee01081967@#$%' # Define in pipeline variables
  azureSubscription: 'multi-stage-sc'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - script: dotnet restore
      displayName: 'Restore NuGet Packages'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build Solution'

    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Test
  displayName: Test Environment
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: TestDeployment
    environment: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: IISWebAppDeploymentOnMachine@0
            inputs:
              WebSiteName: 'TestAPI'
              Package: '$(Pipeline.Workspace)/drop/**/*.zip'
              RemoveAdditionalFilesFlag: true

- stage: Stage
  displayName: Staging Environment
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: StageDeployment
    environment: Stage
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: IISWebAppDeploymentOnMachine@0
            inputs:
              WebSiteName: 'StageAPI'
              Package: '$(Pipeline.Workspace)/drop/**/*.zip'
              RemoveAdditionalFilesFlag: true

- stage: Prod
  displayName: Production Environment
  dependsOn: Stage
  condition: succeeded()
  jobs:
  - deployment: ProdDeployment
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: IISWebAppDeploymentOnMachine@0
            inputs:
              WebSiteName: 'ProdAPI'
              Package: '$(Pipeline.Workspace)/drop/**/*.zip'
              RemoveAdditionalFilesFlag: true