trigger:
  branches:
    include:
      - main

pool:
  name: 'Azure Pipelines'  # Aapka self-hosted agent jo VM me install hai

stages:
- stage: Test
  displayName: 'Deploy to Test'
  jobs:
  - job: DeployTest
    steps:
    - script: |
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/Test
      displayName: 'Build & Publish Test'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/Test'
        TargetFolder: 'C:\inetpub\wwwroot\Test'
      displayName: 'Copy to Test Environment'

- stage: Stage
  displayName: 'Deploy to Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeployStage
    environment: 'Stage'  # Manual approval required
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/Stage
            displayName: 'Build & Publish Stage'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)/Stage'
              TargetFolder: 'C:\inetpub\wwwroot\Stage'
            displayName: 'Copy to Stage Environment'

- stage: Prod
  displayName: 'Deploy to Production'
  dependsOn: Stage
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: 'Prod'  # Manual approval required
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/Prod
            displayName: 'Build & Publish Prod'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)/Prod'
              TargetFolder: 'C:\inetpub\wwwroot\Prod'
            displayName: 'Copy to Production Environment'
